blog/urls.py
from django.conf.urls import url
from blog.views import * # 이렇게 수정하면 아래와 같이 views.~ 형식에서 views. 부분을 빼야 함
                         # bookmark.urls에서는 from . import views로 했으므로 views.~ 형식으로 사용해야 함
#  아래에서 blog/ 부분은 이미 처리되고 넘어온 상황임
urlpatterns = [

    # Example: /
    url(r'^$', PostLV.as_view(), name='index'),

    # Example: /post/ (same as /)
    url(r'^post/$', PostLV.as_view(), name='post_list'),

    # Example: /post/django-example/
    url(r'^post/(?P<slug>[-\w]+)/$', PostDV.as_view(), name='post_detail'),

    # Example: /archive/
    url(r'^archive/$', PostAV.as_view(), name='post_archive'),

    # Example: /2012/
    url(r'^(?P<year>\d{4})/$', PostYAV.as_view(), name='post_year_archive'),

    # # Example: /2012/nov/
    url(r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/$', PostMAV.as_view(), name='post_month_archive'),
    # # Example: /2012/11/
    # url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/$', PostMAV.as_view(), name='post_month_archive'),

    # # Example: /2012/nov/10/
    url(r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/(?P<day>\d{1,2})/$', PostDAV.as_view(), name='post_day_archive'),
    # # Example: /2012/11/10/
    # url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<day>\d{1,2})/$', PostDAV.as_view(), name='post_day_archive'),

    # Example: /today/
    url(r'^today/$', PostTAV.as_view(), name='post_today_archive'),
    # Example: /today/
      url(r'^today/$', PostTAV.as_view(), name='post_today_archive'),

      # /blog/tag/ URL 요청을 처리할 뷰 클래스 지정, 태그 클라우드 출력용 뷰
      # Example: /tag/
      url(r'^tag/$', TagTV.as_view(), name='tag_cloud'),



      # /blog/tag/태그 이름/ 요청을 처리할 뷰 클래스 지정
      # r'...': 이스케이프되지 않는 raw 스트링임을 표시
      # [^/]+ : / 이외 문자가 한번 이상 반복
      # (?u)  : 앞의 표현식을 유니코드로 인식하라고 지정(주소창에 한글 입력 가능하도록)
      # Example: /tag/tagname
      url(r'^tag/(?P<tag>[^/]+(?u))/$', PostTOL.as_view(), name='tagged_object_list'),
    url(r'^search/$', SearchFormView.as_view(), name='search'),

]
# 위에서 지정한 name 항목을 템플릿에서 사용할 때에는 이름공간을 포함하여,
# blog:index, blog:post_list, blog:post_detail, blog:post_archive, ... 로 명시해야 함

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

from mysite.views import HomeView
# 회원 가입 처리 뷰 임포트
from mysite.views import UserCreateView, UserCreateDoneTV         # ch11 1/2

urlpatterns = [
  url(r'^admin/', include(admin.site.urls)),
  # 아래 인증 관련 3행 추가                                        # ch11 2/2
  # 장고 인증 URLconf를 인클루드하여 활용하는데,
  #   여기에 정의된 /login, /logout 등이
  #   실제로는 /accounts/login, /accounts/logout 등으로 처리됨
  url(r'^accounts/', include('django.contrib.auth.urls')), # 로그인, 로그아웃 등 처리(장고 auth에 기본 내장)
  # 계정 가입 처리하는 URL
  url(r'^accounts/register/$', UserCreateView.as_view(), name='register'),
  # 계정 가입 완료될 때 보여줄 URL
  url(r'^accounts/register/done/$', UserCreateDoneTV.as_view(), name='register_done'),

  url(r'^$', HomeView.as_view(), name='home'),
  url(r'^bookmark/', include('bookmark.urls', namespace='bookmark')),
  url(r'^blog/', include('blog.urls', namespace='blog')),
  url(r'^photo/', include('photo.urls', namespace='photo')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>     <!--HTML5 규약을 준수하는 파일-->
  <html lang="ko">    <!--언어는 한국어로 지정--><!---->

  <head>              <!--페이지 타이틀과 css 파일 2개를 연결-->
  <title>{% block title %}Django Web Programming{% endblock %}</title>

  {% load staticfiles %}  <!--정적 파일인 css 연결하기 위하여, staticfiles를 로드-->
  <!--스타일시트 css/base.css 작성이 필요함-->
  <link href="https://fonts.googleapis.com/css?family=Sunflower:300" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="{% block stylesheet %}{% static 'css/base.css' %}{% endblock %}" />
  <link rel="stylesheet" type="text/css" href="{% block extrastyle %}{% endblock %}" />
  <link rel="shortcut icon" href="{% static 'img/logoico.ico' %}">

  </head>
  <body>              <!--바디 영역은 4 영역(헤더/메뉴/콘텐츠/풋터)으로 구성-->

  <div id="header"><!-- ch11 div#header 수정 -->
      <a href="{% url 'home' %}"><img src="{% static 'img/logo2.png' %}" id="headerlogo"></a>
    <ul class="maintitle" style="text-align: center">
      <li class="maintitle"><a href="{% url 'home' %}">홈</a></li>
      <li class="maintitle"><a href="{% url 'bookmark:index' %}">방 찾기</a></li>
      <li class="maintitle"><a href="{% url 'photo:index' %}">방 정보</a></li>
      <li class="maintitle"><a href="{% url 'blog:index' %}">공지사항</a></li>
      <!--<li class="maintitle"><a href="{% url 'blog:post_archive' %}">저장소</a></li>-->
      <!--<li class="maintitle"><a href="{% url 'blog:search' %}">검색</a></li>             &lt;!&ndash;ch09 수정 1/1&ndash;&gt;-->
      <li class="maintitle"><a href="{% url 'admin:index' %}">관리자</a></li>
    </ul>
    <!-- user 객체는 장고 기본 객체이므로 모든 템플릿에서 사용 가능함 -->
    {% if user.is_active %} <!-- 로그인되면 user.is_active() 함수가 참을 반환-->
        <h4 class="welcome">
            <!-- firstof 태그는 뒤에 나오는 인자들 중에서 False 아닌 첫 인자를 선택함 -->
            <strong>{% firstof user.get_short_name user.get_username %}</strong>&nbsp;&nbsp;
            <a href="{% url 'password_change' %}">비밀번호 변경</a>&nbsp;&nbsp;
            <a href="{% url 'logout' %}">로그아웃</a>
        </h4>
    {% else %}
        <h4 class="welcome">
            <a href="{% url 'login' %}">로그인</a>&nbsp;&nbsp;
            <a href="{% url 'register' %}">회원가입</a>
        </h4>
    {% endif %}
</div>


  {% block content %}{% endblock %}   <!--블록 태그로 콘텐츠 영역 정의 -->

  {% block footer %}{% endblock %}    <!--블록 태그로 풋터 영역 정의-->

  </body>
  </html>

templates/home.html
{% extends "base.html" %}                   <!--base.html을 상속받는다고 선언-->

{% block title %}나랑 ♥방구♥할래?{% endblock %}    <!--title 블록 재정의-->

<!--정적 파일인 css 연결하기 위하여, staticfiles를 로드-->
{% load staticfiles %}
<!--extrastyle 블록을 재정의하여 추가적으로 home.css 연결-->
{% block extrastyle %}{% static "css/home.css" %}{% endblock %}

{% block content %}                         <!--content 블록 재정의-->
  <div id="content_home">     <!--content_home 영역 정의-->

      <div id="homeimg">      <!--homeimg 영역 정의-->
          <!--<a href="/"><img src="{% static 'img/iznone.jpg' %}" style="height:256px;"/></a>-->
          <a href="/"><img src="{% static 'img/쿠야광고.gif' %}" style="width:80%;"/></a>
          <!--<h4 style="margin: 0;">장고 프레임워크로 개발한 웹 사이트입니다.</h4>-->
      </div>
      <br/><br/>
      <!--<hr style="margin: 5px 0;">     &lt;!&ndash;그림 및으로 5px 간격을 두고 수평선 넣기&ndash;&gt;-->
      <div id="searchBox"> <input type="text" id="search"><a id="searchButton" href="{% url 'bookmark:index' %}">방 찾기</a><br> </div>
          <!--<form action="." method="post" class="centered"> {% csrf_token %}-->
              <!--{{ form.as_table }}-->
        <!--<input type="text" id="search1"><input type="submit" value="방 찾기" />-->
    <!--</form>-->

      <br/><br/>
      <div id="sortmenu" >
          <h2 style="text-align: center">쉬운 방 찾기</h2>
          <a href="{% url 'photo:index' %}"><img src="{% static 'img/복층원룸2.jpg' %}" style="width:300px;"></a>
          <a href="{% url 'photo:index' %}"><img src="{% static 'img/고양이2.jpg' %}" style="width:300px;"></a>
          <a href="{% url 'photo:index' %}"><img src="{% static 'img/오피스텔.jpg' %}" style="width:300px;"></a>
          <a href="{% url 'photo:index' %}"><img src="{% static 'img/웜룸.jpg' %}" style="width:300px;"></a>
          <a href="{% url 'photo:index' %}"><img src="{% static 'img/아파트.jpg' %}" style="width:300px;"></a>



      </div>

  <br>
      <br>
    <div id="news">

          <div id="news1">
          <h2>공지사항</h2> <button><a id="newsP1" href="{% url 'blog:index' %}">+더보기</a></button>
          <hr>
              <ul>
                  <li><a href="{% url 'blog:index' %}">[이벤트] 방구홈 집들이에 여러분들을 초대합니다!</a></li>
                  <li><a href="{% url 'blog:index' %}">집 구할 때, 꼭 확인해야할 10가지!</a></li>
                  <li><a href="{% url 'blog:index' %}">방구 개인정보처리방침(2018/08/17) 개정안내</a></li>
                  <li><a href="{% url 'blog:index' %}">알면 대박 부동산 꿀팁, 지금 바로 확인해보세요!</a></li>
                  <li><a href="{% url 'blog:index' %}">직접 방문했는데, 허위매물? 헛걸음 보상 신청하기</a></li>


              </ul>
          </div>
          <div id="news2">
              <h2>방구 뉴스</h2> <button><a id="newsP2" href="{% url 'blog:index' %}">+더보기</a></button>
          <hr>
              <ul>
                  <li><a href="{% url 'blog:index' %}">방구의 2018년 신규 광고 영상 1000만 조회수 돌파</a></li>
                  <li><a href="{% url 'blog:index' %}">방9, 끈질긴 허위매물 뿌리 뽑는다</a></li>
                  <li><a href="{% url 'blog:index' %}">[스타트업 굿즈 리뷰] "헛걸음 보상해 드려요"</a></li>
                  <li><a href="{% url 'blog:index' %}">1인 가구 밀집 지역에 ‘방구 케어센터’ 공식 오픈</a></li>
                  <li><a href="{% url 'blog:index' %}">‘방구’, O2O 브랜드 가치 큰폭 상승.. 1위 석권</a></li>
                  <li><a href="{% url 'blog:index' %}">방구, 데이터 분석 센터 구축</a></li>

              </ul>
          </div>
      </div>


  {% endblock content %}

  {% block footer %}                      <!--footer 블록 재정의-->
  <div id="footer">
      <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Copyleft.svg/220px-Copyleft.svg.png"
           height="12" width="12" /> Bang9 Company
  </div>
  {% endblock footer %}